### PR TITLE
Data conversion

### PR DESCRIPTION
**Pull request by nicolasgoedert97**
Conversion methods + unit tests:

SingleCellExperiment <-> AnnData
SingleCellExperiment <-> Matrix + Annotation Vector

### CODE REVIEW

**Comment by PelzKo** [comment]
What is the current status on this? Is this done?

**Comment by nicolasgoedert97** [comment]
Hey sorry did not see your comment, yes theoretically it's done. The only thing missing is that the user can provide a SingleCellExperiment or AnnData directly to the build model function, so that it is converted to matrix automatically. I will add this later today, so if you wait with merging then we can merge the whole at once.

**Comment by PelzKo** [comment]
> 
> 
> Hey sorry did not see your comment, yes theoretically it's done. The only thing missing is that the user can provide a SingleCellExperiment or AnnData directly to the build model function, so that it is converted to matrix automatically. I will add this later today, so if you wait with merging then we can merge the whole at once.

Awesome, then we'll wait :D

**Comment by nicolasgoedert97** [comment]
I changed the build_model function to accept anndata and SCE objects. I wanted to introduce as few new parameters as possible to the function, so i added only one parameter where one can indicate the column name of the cell-type labels in the anndata/SCE object. Alternatively one can still provide this information as vector, as it has been before. @PelzKo If you have time, have a look and tell me if it's good like that or if i should change/remove anything :)

**Comment by nicolasgoedert97** [comment]
Hmm seems like some checks are failing. For Ubuntu (release) it's the same than the one in the main branch but for windows it states: _ERROR: dependencies 'MAST', 'SummarizedExperiment', 'Biobase', 'SingleCellExperiment', 'S4Vectors' are not available for package 'immunedeconv2'_  , weird.

**Comment by grst** [comment]
I fixed the ubuntu release, don't worry about windows, it will probably just start working again in a week or so :roll_eyes:

**Pull request merged**
